server:
  port: 80

spring:
  cloud:
    sentinel:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #允许所有来源访问
            allowedMethods: "*"  #允许所有请求方式跨域访问
            allowedHeaders: "*"
            allowedCredentials: true
      routes:
        - id: incr_test
            uri: lb://service-product
            predicates:
              - Path=/incr

        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: user_route
            uri: lb://service-user
            predicates:
              - Path=/api/user/**

        - id: front_route
          uri: lb://web-front
          predicates:
            - Host=**.gmall.com