server:
  port: 9000
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true

  redis:
    host: 192.168.30.100
    port: 6379
    password: "!Lfy123123@"


app:
  threadpool:
    core-pool-size: 4
    maximum-pool-size: 8
    work-queue-size: 200
    keep-alive-time: 60